import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"

describe("mobile PWA cache boundary", () => {
  test("keeps Collaboration Server paths network-only", () => {
    const source = readFileSync(join(import.meta.dir, "../../vite.config.ts"), "utf8")
    expect(source).toContain('url.pathname.startsWith("/auth/")')
    expect(source).toContain('url.pathname.startsWith("/api/")')
    expect(source).toContain('url.pathname.startsWith("/runs/")')
    expect(source).toContain('url.pathname === "/stream"')
    expect(source).toContain('handler: "NetworkOnly"')
  })

  test("keeps the settings dropdown fully opaque", () => {
    const source = readFileSync(join(import.meta.dir, "mobile-app.tsx"), "utf8")
    const menuStart = source.indexOf('data-testid="mobile-settings-menu"')
    const menuEnd = source.indexOf('data-testid="mobile-logout-button"', menuStart)
    const menuSource = source.slice(menuStart, menuEnd)

    expect(menuSource).toContain("bg-[#fffdfa]")
    expect(menuSource).toContain("opacity-100")
    expect(menuSource).toContain("[background-color:#fffdfa]")
    expect(menuSource).not.toContain("backdrop-blur")
    expect(source).toContain('class="border-b border-[#f0e7e1] bg-[#fffdfa] px-[var(--mobile-field-x)] py-[var(--mobile-field-y)]')
    expect(source).toContain('class="flex w-full items-center gap-2 bg-[#fffdfa] px-[var(--mobile-field-x)] py-[var(--mobile-field-y)]')
  })

  test("adds persistent mobile font size density controls", () => {
    const source = readFileSync(join(import.meta.dir, "mobile-app.tsx"), "utf8")

    expect(source).toContain('const MOBILE_FONT_SIZE_STORAGE_KEY = "gulicode.mobile.font-size"')
    expect(source).toContain('const [mobileFontSize, setMobileFontSize] = createSignal<MobileFontSize>(readMobileFontSize())')
    expect(source).toContain('return isMobileFontSize(value) ? value : "normal"')
    expect(source).toContain('data-mobile-font-size={mobileFontSize()}')
    expect(source).toContain('data-testid="mobile-font-size-setting"')
    expect(source).toContain('{ id: "small", label: "小" }')
    expect(source).toContain('{ id: "normal", label: "标准" }')
    expect(source).toContain('{ id: "large", label: "大" }')
    expect(source).toContain("writeMobileFontSize(value)")
  })

  test("keeps reasoning and tool cards compact when collapsed", () => {
    const source = readFileSync(join(import.meta.dir, "mobile-app.tsx"), "utf8")
    const segmentStart = source.indexOf("function MessageSegmentDisclosure")
    const segmentEnd = source.indexOf("function BlueprintPanel", segmentStart)
    const segmentSource = source.slice(segmentStart, segmentEnd)

    expect(segmentSource).toContain("--mobile-segment-height")
    expect(segmentSource).toContain("--mobile-segment-x")
    expect(segmentSource).toContain("--mobile-segment-expanded-max")
    expect(segmentSource).not.toContain("min-h-7")
    expect(segmentSource).not.toContain("px-2 py-1.5")
    expect(segmentSource).not.toContain("max-h-44")
  })

  test("does not force the Top Agent chat scroll position on every tick", () => {
    const source = readFileSync(join(import.meta.dir, "mobile-app.tsx"), "utf8")

    expect(source).toContain("lastTopAgentScrollKey")
    expect(source).toContain("topAgentChatPinnedToBottom")
    expect(source).toContain("if (scrollKey === lastTopAgentScrollKey) return")
    expect(source).toContain("onScroll={updateTopAgentPinnedState}")
  })

  test("keeps expanded reasoning and tool disclosures open across ticks", () => {
    const source = readFileSync(join(import.meta.dir, "mobile-app.tsx"), "utf8")
    const topAgentStart = source.indexOf("function TopAgentPanel")
    const topAgentEnd = source.indexOf("function MobilePlanningForm", topAgentStart)
    const topAgentSource = source.slice(topAgentStart, topAgentEnd)
    const segmentStart = source.indexOf("function MessageSegmentDisclosure")
    const segmentEnd = source.indexOf("function segmentStatusLabel", segmentStart)
    const segmentSource = source.slice(segmentStart, segmentEnd)

    expect(source).toContain("function segmentDisclosureKey")
    expect(topAgentSource).toContain("openSegmentKeys")
    expect(topAgentSource).toContain("segmentDisclosureWidths")
    expect(topAgentSource).toContain("isSegmentDisclosureOpen")
    expect(topAgentSource).toContain("setSegmentDisclosureOpen")
    expect(topAgentSource).toContain("topAgentChatPinnedToBottom = false")
    expect(topAgentSource).toContain("isSegmentOpen={isSegmentDisclosureOpen}")
    expect(topAgentSource).toContain("onSegmentOpenChange={setSegmentDisclosureOpen}")
    expect(topAgentSource).toContain("segmentWidth={segmentDisclosureWidth}")
    expect(topAgentSource).toContain("onSegmentWidthChange={setSegmentDisclosureWidth}")
    expect(segmentSource).toContain("open={props.open}")
    expect(segmentSource).toContain("width: props.open && props.collapsedWidth")
    expect(segmentSource).toContain('"max-width": "100%"')
    expect(segmentSource).toContain("onOpenChange={handleOpenChange}")
    expect(segmentSource).toContain("measureCollapsedWidth")
    expect(segmentSource).toContain("overflow-x-auto")
    expect(segmentSource).not.toContain("createSignal(false)")
  })

  test("renders desktop chat as one localized chat box", () => {
    const source = readFileSync(join(import.meta.dir, "mobile-app.tsx"), "utf8")
    const topAgentStart = source.indexOf("function TopAgentPanel")
    const topAgentEnd = source.indexOf("function MobilePlanningForm", topAgentStart)
    const topAgentSource = source.slice(topAgentStart, topAgentEnd)
    const chatIndex = topAgentSource.indexOf('data-testid="mobile-top-agent-chat"')
    const formIndex = topAgentSource.indexOf('data-testid="mobile-desktop-message-form"')

    expect(chatIndex).toBeGreaterThan(-1)
    expect(formIndex).toBeGreaterThan(chatIndex)
    expect(topAgentSource).toContain('class="flex min-h-0 w-full min-w-0 flex-1 flex-col gap-[var(--mobile-section-gap)]"')
    expect(topAgentSource).toContain('class="flex min-h-0 w-full min-w-0 flex-1 flex-col rounded-md')
    expect(topAgentSource).toContain('class="min-h-0 flex-1 overflow-y-auto')
    expect(topAgentSource).not.toContain("max-h-56")
    expect(topAgentSource).toContain('class="mt-[var(--mobile-card-p)] grid shrink-0 gap-[var(--mobile-gap)] border-t border-[#f0e7e1] pt-[var(--mobile-card-p)]"')
    expect(topAgentSource).toContain(">聊天<")
    expect(topAgentSource).toContain("w-full min-w-0")
    expect(topAgentSource).toContain("发送消息")
    expect(topAgentSource).toContain("发送到桌面当前会话")
    expect(topAgentSource).toContain('data-testid="mobile-desktop-session-clear"')
    expect(topAgentSource).toContain("清空")
    expect(topAgentSource).toContain('data-testid="mobile-desktop-message-mode"')
    expect(topAgentSource).toContain("等待桌面模式")
    expect(topAgentSource).toContain("composerModes()")
    expect(topAgentSource).not.toContain('<option value="default">')
    expect(topAgentSource).not.toContain('<option value="top">')
    expect(topAgentSource).not.toContain("普通")
    expect(topAgentSource).toContain("就绪")
    expect(source).toContain("function segmentStatusLabel")
    expect(source).toContain('case "completed"')
    expect(source).toContain('return "完成"')
    expect(topAgentSource).not.toContain("Desktop chat")
    expect(topAgentSource).not.toContain("Message desktop")
    expect(topAgentSource).not.toContain("Ready")
    expect(topAgentSource).not.toContain(">Send<")
  })

  test("moves the planning form to the top of the blueprint tab", () => {
    const source = readFileSync(join(import.meta.dir, "mobile-app.tsx"), "utf8")
    const blueprintStart = source.indexOf("function BlueprintPanel")
    const blueprintEnd = source.indexOf("function AgentInfoSheet", blueprintStart)
    const blueprintSource = source.slice(blueprintStart, blueprintEnd)
    const planningIndex = blueprintSource.indexOf("<MobilePlanningForm")
    const structureIndex = blueprintSource.indexOf('data-testid="blueprint-structure-preview"')

    expect(planningIndex).toBeGreaterThan(-1)
    expect(planningIndex).toBeLessThan(structureIndex)
    expect(source).toContain("蓝图目标")
    expect(source).toContain("描述需要顶层代理规划的蓝图任务")
    expect(source).toContain("开始规划")
    expect(source).not.toContain("Mobile goal")
    expect(source).not.toContain("Describe what Top Agent should plan")
    expect(source).not.toContain("Start planning")
  })

  test("renders typed blueprint node details for full desktop mirrors", () => {
    const source = readFileSync(join(import.meta.dir, "mobile-app.tsx"), "utf8")
    const stateSource = readFileSync(join(import.meta.dir, "mobile-state.ts"), "utf8")
    const apiSource = readFileSync(join(import.meta.dir, "mobile-api.ts"), "utf8")

    expect(stateSource).toContain('export type BlueprintNodeKind = "agent" | "worker_agent" | "script" | "branch" | "tick"')
    expect(source).toContain("function NodeTypeDetails")
    expect(source).toContain('data-testid="node-type-details"')
    expect(source).toContain("nodeKindLabel(props.node.kind)")
    expect(source).toContain('props.node.kind === "agent" || props.node.kind === "worker_agent"')
    expect(source).toContain("移动端只展示同步信息，不提供编辑或执行入口")
    expect(apiSource).toContain("projected.outputPort = edge.outputPort")
    expect(apiSource).toContain("projected.inputPort = edge.inputPort")
    expect(apiSource).toContain("everyNTicks: node.everyNTicks")
  })
})
