import type { MobileProject, MobileRun } from "./mobile-state"

export const mockProjects: MobileProject[] = [
  {
    id: "proj-gulicode",
    name: "GuLiCode Desktop",
    description: "Runtime binding, blueprint panel, and workspace review.",
    owner: "QHX",
    activeRunCount: 3,
  },
  {
    id: "proj-sdk",
    name: "Collaboration SDK",
    description: "API contracts for mobile dispatch and event replay.",
    owner: "Platform",
    activeRunCount: 1,
  },
  {
    id: "proj-docs",
    name: "Release Notes",
    description: "Reports, acceptance notes, and rollout checklists.",
    owner: "Docs",
    activeRunCount: 2,
  },
]

export const mockRuns: MobileRun[] = [
  {
    id: "run-runtime-smoke",
    projectId: "proj-gulicode",
    title: "Blueprint runtime smoke",
    instruction: "Validate the staged runtime overlay and summarize blocked nodes.",
    blueprint: "runtime-control-plane",
    status: "running",
    priority: "high",
    progress: 68,
    cursor: 44,
    updatedAt: "2026-05-27T10:18:00.000+08:00",
    agents: ["top-agent", "planner", "runtime-smoke", "review"],
    events: [
      {
        id: "evt-runtime-4",
        kind: "agent",
        title: "review",
        body: "Found one pending join that needs user approval before archive.",
        time: "10:18",
      },
      {
        id: "evt-runtime-3",
        kind: "tool",
        title: "workspace diff",
        body: "Generated a changeset index with 5 touched files.",
        time: "10:11",
      },
      {
        id: "evt-runtime-2",
        kind: "status",
        title: "runtime status",
        body: "planner and runtime-smoke completed; review is running.",
        time: "10:05",
      },
      {
        id: "evt-runtime-1",
        kind: "status",
        title: "run accepted",
        body: "Top Agent started the requested smoke flow.",
        time: "09:54",
      },
    ],
    tools: [
      {
        id: "tool-runtime-status",
        title: "runtime status",
        state: "done",
        description: "Latest snapshot received through the mock event journal.",
      },
      {
        id: "tool-workspace-diff",
        title: "workspace diff",
        state: "running",
        description: "Collecting changed files for mobile report preview.",
      },
    ],
    reports: [
      {
        id: "report-runtime-summary",
        title: "Runtime smoke summary",
        kind: "summary",
        ready: true,
      },
      {
        id: "report-runtime-changeset",
        title: "Changeset index",
        kind: "changeset",
        ready: true,
      },
    ],
  },
  {
    id: "run-blueprint-review",
    projectId: "proj-gulicode",
    title: "Review blueprint panel changes",
    instruction: "Check pending UI states before the next desktop smoke pass.",
    blueprint: "panel-review",
    status: "needs-review",
    priority: "normal",
    progress: 92,
    cursor: 31,
    updatedAt: "2026-05-27T09:45:00.000+08:00",
    agents: ["top-agent", "ui-review"],
    events: [
      {
        id: "evt-review-3",
        kind: "report",
        title: "report ready",
        body: "UI review report is available for approval.",
        time: "09:45",
      },
      {
        id: "evt-review-2",
        kind: "agent",
        title: "ui-review",
        body: "No blocker found. One layout note is included in the report.",
        time: "09:41",
      },
      {
        id: "evt-review-1",
        kind: "status",
        title: "review queued",
        body: "Waiting for mobile approval.",
        time: "09:30",
      },
    ],
    tools: [
      {
        id: "tool-playwright-shot",
        title: "Playwright screenshot",
        state: "done",
        description: "Mobile-sized panel screenshot attached to the report.",
      },
    ],
    reports: [
      {
        id: "report-panel-review",
        title: "Blueprint panel review",
        kind: "summary",
        ready: true,
      },
    ],
  },
  {
    id: "run-sdk-contract",
    projectId: "proj-sdk",
    title: "Draft run event contract",
    instruction: "Prepare the minimal mobile event envelope for SSE replay.",
    blueprint: "api-contract",
    status: "paused",
    priority: "normal",
    progress: 46,
    cursor: 18,
    updatedAt: "2026-05-27T08:52:00.000+08:00",
    agents: ["top-agent", "api-writer"],
    events: [
      {
        id: "evt-sdk-2",
        kind: "action",
        title: "paused",
        body: "Paused while service boundary stays out of this UI-only pass.",
        time: "08:52",
      },
      {
        id: "evt-sdk-1",
        kind: "agent",
        title: "api-writer",
        body: "Drafted event names for status, agent utterance, tool card, and report.",
        time: "08:40",
      },
    ],
    tools: [
      {
        id: "tool-contract-note",
        title: "contract note",
        state: "blocked",
        description: "Blocked until the Collaboration Server implementation starts.",
      },
    ],
    reports: [],
  },
  {
    id: "run-docs-release",
    projectId: "proj-docs",
    title: "Prepare mobile PWA notes",
    instruction: "Summarize the PWA scope and follow-up server tasks.",
    blueprint: "release-note",
    status: "completed",
    priority: "normal",
    progress: 100,
    cursor: 25,
    updatedAt: "2026-05-26T19:20:00.000+08:00",
    agents: ["top-agent", "doc-writer"],
    events: [
      {
        id: "evt-docs-2",
        kind: "report",
        title: "summary ready",
        body: "Acceptance notes are ready.",
        time: "19:20",
      },
      {
        id: "evt-docs-1",
        kind: "agent",
        title: "doc-writer",
        body: "Captured PWA-only constraints and service boundary notes.",
        time: "19:12",
      },
    ],
    tools: [
      {
        id: "tool-docs-link",
        title: "docs index",
        state: "done",
        description: "Linked the mobile PWA design document.",
      },
    ],
    reports: [
      {
        id: "report-docs-summary",
        title: "PWA rollout notes",
        kind: "summary",
        ready: true,
      },
      {
        id: "report-docs-artifact",
        title: "Acceptance checklist",
        kind: "artifact",
        ready: true,
      },
    ],
  },
]
