import { describe, expect, test } from "bun:test"

describe("session blueprint planning source", () => {
  test("keeps normal chat on the normal path and gates planning behind blueprint mode", async () => {
    const sessionSource = (await Bun.file(new URL("../session.tsx", import.meta.url)).text()).replaceAll("\r\n", "\n")
    const promptInputSource = (
      await Bun.file(new URL("../../components/prompt-input.tsx", import.meta.url)).text()
    ).replaceAll("\r\n", "\n")
    const sessionSidePanelSource = (
      await Bun.file(new URL("./session-side-panel.tsx", import.meta.url)).text()
    ).replaceAll("\r\n", "\n")
    const submitSource = (
      await Bun.file(new URL("../../components/prompt-input/submit.ts", import.meta.url)).text()
    ).replaceAll("\r\n", "\n")

    expect(promptInputSource).toContain('"blueprintPlanning"')
    expect(promptInputSource).toContain('"蓝图规划"')
    expect(submitSource).toContain('mode === "blueprintPlanning"')
    expect(submitSource).not.toContain('mode === "normal" && !text.startsWith("/") && input.submitOverride')

    expect(sessionSource).toContain("ensureBlueprintPlanningContext")
    expect(sessionSource).toContain("input.projectDirectory,\n      blueprintId")
    expect(sessionSource).toContain("sdk.client.mcp.add")
    expect(sessionSource).toContain("directory: sdk.directory")
    expect(sessionSource).toContain("blueprintPlanningMcpStatusMap(added.data, name)")
    expect(sessionSource).not.toContain("sdk.client.mcp.status")
    expect(sessionSource).not.toContain("sdk.client.mcp.connect")
    expect(sessionSource).toContain("current?.status !== \"connected\"")
    expect(sessionSource).toContain("answerBlueprintPlanningQuestion")
    expect(sessionSource).toContain("rejectBlueprintPlanningPlan")
    expect(sessionSource).toContain("markBlueprintPlanningPlanStarted")
    expect(sessionSource).toContain("cloneBlueprintPlanningPayload(plan)")
    expect(sessionSource).toContain("blueprintPlanning.contextBlueprintId || blueprintPlanning.blueprintId || DEFAULT_BLUEPRINT_ID")
    expect(sessionSource).toContain("requestBlueprintPlanningSubmit")
    expect(sessionSource).toContain("silentBlocked")
    expect(sessionSource).toContain("setBlueprintPlanningSubmitRequest")
    expect(sessionSource).toContain("claimedRequestId")
    expect(sessionSource).toContain("claimMobilePlanningRequest")
    expect(sessionSource).toContain("desktopSessionId: blueprintPlanning.desktopSessionId")
    expect(sessionSource).toContain("onBlocked: () => clearMobilePlanningRelayRequest(request.id)")
    expect(sessionSource).toContain('item.status === "planning" && !item.desktopSessionId && !item.planningSessionId')
    expect(sessionSource).toContain("!blueprintPlanning.sessionId &&")
    expect(sessionSource).toContain("if (!blueprintPlanningAvailable() || isChildSession()) return")
    expect(sessionSource).toContain("body: JSON.stringify({ desktopSessionId })")
    expect(sessionSource).not.toContain("if (!params.id || !blueprintPlanningAvailable() || isChildSession()) return")
    expect(sessionSource).not.toContain("body: JSON.stringify({ desktopSessionId: params.id })")
    expect(sessionSource).not.toContain("planning-requests?status=pending_desktop")
    expect(sessionSource).toContain("blueprintPlanningSubmitRequest={blueprintPlanningSubmitRequest()}")
    expect(sessionSource).toContain("const blueprintPlanningProgress = createMemo")
    expect(sessionSource).toContain("planningRequested: false")
    expect(sessionSource).toContain("blueprintPlanning.planningRequested")
    expect(sessionSource).toContain("if (!input.silentBlocked) setBlueprintPlanning({ desktopSessionId: params.id, planningRequested: true, blueprintId })")
    expect(sessionSource).toContain('setBlueprintPlanning("planningRequested", false)')
    expect(sessionSource).toContain("!blueprintPlanning.planningRequested")
    expect(sessionSource).toContain("void platform\n      .blueprintPlanningStatus?.(sessionId)")
    expect(sessionSource).toContain("}, 15_000)")
    expect(sessionSource).toContain('phase: "start"')
    expect(sessionSource).toContain('phase: "planning"')
    expect(sessionSource).toContain("blueprintPlanningProgress={blueprintPlanningProgress()}")
    expect(sessionSidePanelSource).toContain("blueprintPlanningProgress?: BlueprintPlanningProgressState")
    expect(sessionSidePanelSource).toContain("blueprintPlanningProgress={props.blueprintPlanningProgress}")
    expect(promptInputSource).toContain("props.blueprintPlanningSubmitRequest")
    expect(promptInputSource).toContain('setMode("blueprintPlanning")')
    expect(promptInputSource).toContain("void handleSubmit(new Event(\"submit\", { cancelable: true }))")
    expect(sessionSource).not.toContain("sendBlueprintTopAgentMessage")
    expect(sessionSource).not.toContain("TopAgentTimeline")
  })
})
